// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.


export class CreateProjectParams {
    name = ""
    uid = ""
    author = ""
    description = ""
    folder = ""

}

export class LastProjectInfo {
    name = ""
    path = ""
    uid = ""
    lastModified = ""
    exists = false

    FromJson(jObj: any) {
        this.name = jObj.name ?? ""
        this.path = jObj.path ?? ""
        this.uid = jObj.uid ?? ""
        this.exists = jObj.exists ?? false
        this.lastModified = jObj.lastModified ?? ""
    }

}