// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.


export class ProjectLight {
    uid = ""
    name = ""
    description = ""
    author = ""
    project_type = ""
    lat_lon = ""
    projectFolderPath = ""

    from_json(jObject: any | ProjectLight) {


        this.uid = jObject.uid ?? ""
        this.name = jObject.name ?? ""
        this.description = jObject.description ?? ""
        this.author = jObject.author ?? ""
        this.lat_lon = jObject.lat_lon ?? ""
        this.projectFolderPath = jObject.projectFolderPath ?? ""

    }

    static ArrayFromJsonArray(jarray: any): Array<ProjectLight> {
        const projects = jarray.map((value) => {
            const tmp = new ProjectLight()
            tmp.from_json(value)
            return tmp
        })

        return projects
    }


}