// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export class Project {
    uid = ""
    name = ""
    description = ""
    author = ""
    at = 0
    tauri_projectFolderPath = ""

    FromJson(jObject: any | Project) {
        this.uid = jObject.uid ?? ""
        this.name = jObject.name ?? ""
        this.author = jObject.author ?? ""
        this.description = jObject.description ?? ""
        this.tauri_projectFolderPath = jObject.projectFolderPath ?? ""

    }

    ToJson(): any {
        return {
            uid: this.uid,
            name: this.name,
            description: this.description,
            author: this.author,
            at: this.at
        }
    }

    static ArrayFromJsonArray(jarray: any): Array<Project> {
        const projects = jarray.map((value) => {
            const tmp = new Project()
            tmp.FromJson(value)
            return tmp
        })

        return projects
    }


}